# Generated by Django 3.1.7 on 2021-03-28 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPG_to_PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='JPG_to_PDF/user_uploads')),
                ('time', models.DateField(default=datetime.datetime(2021, 3, 28, 11, 7, 14, 322635))),
            ],
        ),
    ]
