# Generated by Django 3.1.7 on 2021-03-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpg_to_pdf',
            name='time',
            field=models.TimeField(default=46),
        ),
    ]
