# Generated by Django 3.1.7 on 2021-03-29 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_pdf', '0002_auto_20210328_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpg_to_pdf',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 29, 3, 21, 37, 985286)),
        ),
    ]
