# Generated by Django 3.2.3 on 2021-07-02 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_pdf', '0003_auto_20210329_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='jpg_to_pdf',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 2, 7, 57, 47, 511976)),
        ),
    ]
